### ISSUE TITLE
Unable to launch Husky Gazebo simulator noetic-devel

### ISSUE THREAD

**Issue by EricWiener** [husky/husky#157]
I started with a clean noetic environment:
```
mkdir -p ~/catkin_ws/src
$ cd ~/catkin_ws/src
$ sudo apt-get install ros-noetic-desktop-full
$ git clone https://github.com/clearpathrobotics/LMS1xx.git
$ git clone https://github.com/husky/husky.git
$ cd husky
$ git checkout noetic-devel
$ cd ~/catkin_ws
$ rosdep install --from-paths src --ignore-src --rosdistro ${ROS_DISTRO} -y --as-root pip:no
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
husky_bringup: Cannot locate rosdep definition for [um7]
husky_control: Cannot locate rosdep definition for [multimaster_launch]
husky_gazebo: Cannot locate rosdep definition for [multimaster_launch]
```

Wasn't sure how to solve that last issue (it seems [um7](http://wiki.ros.org/um7) is only available on melodic), but I was successfully able to run:
```
catkin_make
source devel/setup.bash
```

But when I try to run Gazebo, I get the following error:
```
roslaunch husky_gazebo husky_empty_world.launch 
... logging to /root/.ros/log/6ae6a5e4-5e74-11eb-9a3b-0de85a64961c/roslaunch-cpr-mic09-31077.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://cpr-mic09:36295/

SUMMARY
========

PARAMETERS
 * /ekf_localization/base_link_frame: base_link
 * /ekf_localization/frequency: 50
 * /ekf_localization/imu0: imu/data
 * /ekf_localization/imu0_config: [False, False, Fa...
 * /ekf_localization/imu0_differential: True
 * /ekf_localization/imu0_queue_size: 10
 * /ekf_localization/imu0_remove_gravitational_acceleration: True
 * /ekf_localization/odom0: husky_velocity_co...
 * /ekf_localization/odom0_config: [False, False, Fa...
 * /ekf_localization/odom0_differential: False
 * /ekf_localization/odom0_queue_size: 10
 * /ekf_localization/odom_frame: odom
 * /ekf_localization/two_d_mode: True
 * /ekf_localization/world_frame: odom
 * /gazebo/enable_ros_network: True
 * /husky_joint_publisher/publish_rate: 50
 * /husky_joint_publisher/type: joint_state_contr...
 * /husky_velocity_controller/angular/z/has_acceleration_limits: True
 * /husky_velocity_controller/angular/z/has_velocity_limits: True
 * /husky_velocity_controller/angular/z/max_acceleration: 6.0
 * /husky_velocity_controller/angular/z/max_velocity: 2.0
 * /husky_velocity_controller/base_frame_id: base_link
 * /husky_velocity_controller/cmd_vel_timeout: 0.25
 * /husky_velocity_controller/enable_odom_tf: False
 * /husky_velocity_controller/estimate_velocity_from_position: False
 * /husky_velocity_controller/left_wheel: ['front_left_whee...
 * /husky_velocity_controller/linear/x/has_acceleration_limits: True
 * /husky_velocity_controller/linear/x/has_velocity_limits: True
 * /husky_velocity_controller/linear/x/max_acceleration: 3.0
 * /husky_velocity_controller/linear/x/max_velocity: 1.0
 * /husky_velocity_controller/pose_covariance_diagonal: [0.001, 0.001, 0....
 * /husky_velocity_controller/publish_rate: 50
 * /husky_velocity_controller/right_wheel: ['front_right_whe...
 * /husky_velocity_controller/twist_covariance_diagonal: [0.001, 0.001, 0....
 * /husky_velocity_controller/type: diff_drive_contro...
 * /husky_velocity_controller/velocity_rolling_window_size: 2
 * /husky_velocity_controller/wheel_radius_multiplier: 1.0
 * /husky_velocity_controller/wheel_separation_multiplier: 1.875
 * /joy_teleop/joy_node/autorepeat_rate: 20
 * /joy_teleop/joy_node/deadzone: 0.1
 * /joy_teleop/joy_node/dev: /dev/input/ps4
 * /joy_teleop/teleop_twist_joy/axis_angular: 0
 * /joy_teleop/teleop_twist_joy/axis_linear: 1
 * /joy_teleop/teleop_twist_joy/enable_button: 4
 * /joy_teleop/teleop_twist_joy/enable_turbo_button: 5
 * /joy_teleop/teleop_twist_joy/scale_angular: 1.4
 * /joy_teleop/teleop_twist_joy/scale_linear: 0.4
 * /joy_teleop/teleop_twist_joy/scale_linear_turbo: 2.0
 * /robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.15.9
 * /twist_mux/locks: [{'name': 'e_stop...
 * /twist_mux/topics: [{'name': 'joy', ...
 * /use_sim_time: True

NODES
  /
    base_controller_spawner (controller_manager/spawner)
    ekf_localization (robot_localization/ekf_localization_node)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    spawn_husky_model (gazebo_ros/spawn_model)
    twist_marker_server (interactive_marker_twist_server/marker_server)
    twist_mux (twist_mux/twist_mux)
  /joy_teleop/
    joy_node (joy/joy_node)
    teleop_twist_joy (teleop_twist_joy/teleop_node)

ROS_MASTER_URI=http://localhost:11311

process[gazebo-1]: started with pid [31087]
process[gazebo_gui-2]: started with pid [31092]
process[base_controller_spawner-3]: started with pid [31095]
ERROR: cannot launch node of type [robot_localization/ekf_localization_node]: robot_localization
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/ubuntu/catkin_ws/src
ROS path [2]=/opt/ros/noetic/share
ERROR: cannot launch node of type [interactive_marker_twist_server/marker_server]: interactive_marker_twist_server
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/ubuntu/catkin_ws/src
ROS path [2]=/opt/ros/noetic/share
process[robot_state_publisher-6]: started with pid [31098]
ERROR: cannot launch node of type [twist_mux/twist_mux]: twist_mux
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/ubuntu/catkin_ws/src
ROS path [2]=/opt/ros/noetic/share
ERROR: cannot launch node of type [joy/joy_node]: joy
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/ubuntu/catkin_ws/src
ROS path [2]=/opt/ros/noetic/share
ERROR: cannot launch node of type [teleop_twist_joy/teleop_node]: teleop_twist_joy
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/ubuntu/catkin_ws/src
ROS path [2]=/opt/ros/noetic/share
process[spawn_husky_model-10]: started with pid [31099]
[ERROR] [1611536359.218983933]: Failed to build tree: child link [base_laser_mount] of joint [laser_mount_joint] not found
[robot_state_publisher-6] process has died [pid 31098, exit code 1, cmd /opt/ros/noetic/lib/robot_state_publisher/robot_state_publisher __name:=robot_state_publisher __log:=/root/.ros/log/6ae6a5e4-5e74-11eb-9a3b-0de85a64961c/robot_state_publisher-6.log].
log file: /root/.ros/log/6ae6a5e4-5e74-11eb-9a3b-0de85a64961c/robot_state_publisher-6*.log
[ INFO] [1611536360.402585265]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1611536360.407477778]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1611536360.584057835]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1611536360.589816492]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1611536360.753414765]: waitForService: Service [/gazebo/set_physics_properties] is now available.
Aborted (core dumped)
[gazebo_gui-2] process has died [pid 31092, exit code 134, cmd /opt/ros/noetic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/root/.ros/log/6ae6a5e4-5e74-11eb-9a3b-0de85a64961c/gazebo_gui-2.log].
log file: /root/.ros/log/6ae6a5e4-5e74-11eb-9a3b-0de85a64961c/gazebo_gui-2*.log
Error [parser_urdf.cc:3193] Unable to call parseURDF on robot model
Error [parser.cc:488] parse as old deprecated model file failed.
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 522, in call
    responses = transport.receive_once()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 737, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 109, in recv_buff
    raise TransportTerminated("unable to receive data from sender, check sender's logs for details")
rospy.exceptions.TransportTerminated: unable to receive data from sender, check sender's logs for details

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/catkin_ws/devel/lib/controller_manager/spawner", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/ubuntu/catkin_ws/src/ros_control/controller_manager/scripts/spawner", line 212, in <module>
    if __name__ == '__main__': main()
  File "/home/ubuntu/catkin_ws/src/ros_control/controller_manager/scripts/spawner", line 190, in main
    resp = load_controller(name)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 532, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
[WARN] [1611536361.900845, 1.054000]: Controller Spawner error while taking down controllers: unable to connect to service: [Errno 111] Connection refused
[base_controller_spawner-3] process has died [pid 31095, exit code 1, cmd /home/ubuntu/catkin_ws/devel/lib/controller_manager/spawner husky_joint_publisher husky_velocity_controller __name:=base_controller_spawner __log:=/root/.ros/log/6ae6a5e4-5e74-11eb-9a3b-0de85a64961c/base_controller_spawner-3.log].
log file: /root/.ros/log/6ae6a5e4-5e74-11eb-9a3b-0de85a64961c/base_controller_spawner-3*.log
^C[spawn_husky_mo
```

**Comment by civerachb-cpr** [comment]
The noetic branch is still being worked-on and hasn't been officially released yet.  Several of Husky's third-party dependencies have not yet been updated for Noetic.  And several files & scripts within the Husky repo still use older Kinetic/Melodic era formats (e.g. Python 2 scripts that need to be updated to Python 3).

**Comment by EricWiener** [comment]
Got it. Thank you.

**Comment by anjulo** [comment]
Hello,

So, when will the official noetic branch will be released?

Thank you.

**Comment by civerachb-cpr** [comment]
We don't have an "official" release date targeted.  We're hoping to have all of our in-house testing on the physical robot done by the end of the summer.
For now, the husky_gazebo package in the noetic-devel branch is usable in Noetic if you need  to use the simulation environment (which is what this issue was originally asking about).
